export const categories = [
  {
    name: 'Healing Ointments',
    slug: 'healing-ointments',
    description: 'Premium cannabis-infused healing salves and ointments crafted with care for natural relief and restoration.',
    image: '/assets/products/category-ointments.jpg',
  },
  {
    name: 'Apparel',
    slug: 'apparel',
    description: 'Express your lifestyle with our premium Highly Medicated apparel collection.',
    image: '/assets/products/category-apparel.jpg',
  },
  {
    name: 'Merchandise',
    slug: 'merchandise',
    description: 'Exclusive Highly Medicated merchandise for the conscious community.',
    image: '/assets/products/category-merchandise.jpg',
  },
];

export const products = [
  // Healing Ointments
  {
    name: 'CannaSalve Original',
    slug: 'cannasalve-original',
    description: 'Our signature healing salve infused with premium cannabis extract and natural botanicals. Formulated for deep muscle relief and skin restoration.',
    longDescription: `CannaSalve Original is our flagship healing product, crafted with a carefully curated blend of cannabis extract, shea butter, coconut oil, and essential botanicals. Each jar is hand-made in small batches to ensure the highest quality and potency.\n\nDesigned for those seeking natural relief from muscle tension, joint discomfort, and skin irritation. The rich, nourishing formula absorbs quickly and provides long-lasting comfort.\n\nOur proprietary extraction process preserves the full spectrum of beneficial compounds, working in harmony with your body's natural healing processes.`,
    price: 350,
    comparePrice: 450,
    sku: 'HM-CS-001',
    stock: 50,
    images: ['/assets/products/Lid_label.png', '/assets/products/Lid_label.png'],
    featured: true,
    weight: '100ml',
    ingredients: 'Cannabis extract, Shea butter, Coconut oil, Beeswax, Lavender essential oil, Eucalyptus essential oil, Vitamin E',
    usage: 'Apply a small amount to the affected area and massage gently. Use 2-3 times daily or as needed. For external use only.',
    benefits: 'Natural pain relief, Anti-inflammatory, Skin nourishment, Muscle relaxation, Deep moisturizing',
    categorySlug: 'healing-ointments',
  },
  {
    name: 'CannaSalve Extra Strength',
    slug: 'cannasalve-extra-strength',
    description: 'Enhanced formula with double the potency for deep tissue relief and accelerated healing. Perfect for active lifestyles.',
    longDescription: `CannaSalve Extra Strength takes our beloved original formula to the next level. With double the concentration of cannabis extract and added arnica and menthol, this powerful salve delivers targeted relief where you need it most.\n\nIdeal for athletes, active individuals, and anyone seeking more intensive support for their recovery journey. The cooling menthol provides immediate comfort while the cannabis extract works deep within the tissues.`,
    price: 550,
    comparePrice: 650,
    sku: 'HM-CS-002',
    stock: 35,
    images: ['/assets/products/Lid_label.png', '/assets/products/Lid_label.png'],
    featured: true,
    weight: '100ml',
    ingredients: 'Double-strength cannabis extract, Arnica montana, Menthol, Shea butter, Coconut oil, Beeswax, Peppermint essential oil, Rosemary essential oil',
    usage: 'Apply to affected areas with gentle circular motions. Allow to absorb fully. Use up to 3 times daily. Avoid contact with eyes and open wounds.',
    benefits: 'Extra-strength pain relief, Deep tissue recovery, Anti-inflammatory, Cooling sensation, Athletic recovery',
    categorySlug: 'healing-ointments',
  },
  // Apparel
  {
    name: 'Highly Medicated Classic Tee',
    slug: 'hm-classic-tee',
    description: 'Premium cotton tee featuring the Highly Medicated logo. Comfortable, stylish, and perfect for everyday wear.',
    longDescription: `Our Classic Tee is made from 100% organic cotton, ensuring maximum comfort while supporting sustainable practices. The Highly Medicated logo is screen-printed using eco-friendly inks that maintain their vibrancy wash after wash.\n\nAvailable in multiple sizes, this tee features a relaxed fit that flatters all body types. Whether you're lounging at home or heading out, this tee makes a statement.`,
    price: 299,
    comparePrice: 399,
    sku: 'HM-AT-001',
    stock: 100,
    images: ['/assets/products/tshirt1.png', '/assets/products/tshirt2.png'],
    featured: true,
    weight: '200g',
    categorySlug: 'apparel',
  },
  {
    name: 'Highly Medicated Hoodie',
    slug: 'hm-hoodie',
    description: 'Cozy premium hoodie with embroidered Highly Medicated branding. The ultimate comfort piece for cooler days.',
    longDescription: `Wrap yourself in comfort with our premium Highly Medicated Hoodie. Crafted from a luxurious cotton-polyester blend, this hoodie features a soft brushed interior that feels incredible against the skin.\n\nThe embroidered logo adds a touch of sophistication, while the kangaroo pocket and adjustable drawstring hood provide practical functionality. A wardrobe essential for the Cape Town winters.`,
    price: 599,
    comparePrice: 750,
    sku: 'HM-AH-001',
    stock: 60,
    images: ['/assets/products/hoodie.png', '/assets/products/hoodie.png'],
    featured: false,
    weight: '450g',
    categorySlug: 'apparel',
  },
  // Merchandise
  {
    name: 'Highly Medicated Rolling Tray',
    slug: 'hm-rolling-tray',
    description: 'Custom-designed rolling tray featuring original Highly Medicated artwork. Functional meets artistic.',
    longDescription: `Our signature Rolling Tray is more than just a functional accessory; it is a piece of art. Featuring custom artwork by local Cape Town artists, each tray is crafted from durable, high-quality metal with a smooth, easy-to-clean surface.\n\nThe raised edges prevent spills while the vibrant, UV-resistant print ensures your tray stays looking fresh for years to come.`,
    price: 199,
    comparePrice: 250,
    sku: 'HM-MT-001',
    stock: 75,
    images: ['/assets/products/rolling_tray.png', '/assets/products/rolling_tray.png'],
    featured: true,
    weight: '300g',
    categorySlug: 'merchandise',
  },
  {
    name: 'Highly Medicated Premium Grinder',
    slug: 'hm-premium-grinder',
    description: 'High-quality 4-piece aluminum grinder with Highly Medicated branding. Precision-cut teeth for perfect grinding.',
    longDescription: `Experience the difference quality makes with our Premium Grinder. Crafted from aircraft-grade aluminum with diamond-cut teeth, this 4-piece grinder delivers consistent results every time.\n\nThe magnetic lid keeps everything secure while the fine mesh kief catcher ensures you never waste any precious material. Featuring laser-etched Highly Medicated branding that will never fade or wear off.\n\nSmooth threading and a comfortable grip make this grinder a joy to use. Compact enough for travel yet substantial enough for daily use.`,
    price: 249,
    comparePrice: 320,
    sku: 'HM-MG-001',
    stock: 85,
    images: ['/assets/products/grinder.png', '/assets/products/grinder.png'],
    featured: false,
    categorySlug: 'merchandise',
  },
];

export const blogPosts = [
  {
    title: 'The Healing Power of Cannabis Topicals',
    slug: 'healing-power-cannabis-topicals',
    excerpt: 'Discover how cannabis-infused topicals are revolutionizing natural pain relief and skin care in South Africa.',
    content: `Cannabis topicals have been used for centuries across various cultures for their remarkable healing properties. In recent years, South Africa has seen a growing appreciation for these natural remedies, backed by modern scientific research.\n\n## How Cannabis Topicals Work\n\nUnlike other forms of cannabis consumption, topicals work by interacting with cannabinoid receptors in the skin. They do not enter the bloodstream, meaning they provide localized relief without any psychoactive effects.\n\nThe endocannabinoid system (ECS) in our skin responds to compounds found in cannabis, particularly CBD and THC, to help regulate pain, inflammation, and skin cell production.\n\n## Benefits of Cannabis Topicals\n\n- **Pain Relief**: Studies show that cannabis topicals can effectively reduce chronic pain and inflammation\n- **Skin Health**: The antioxidant properties help combat signs of aging and promote healthy skin\n- **Muscle Recovery**: Athletes and active individuals benefit from faster recovery times\n- **Stress Relief**: Many users report a calming, soothing sensation upon application\n\n## The Highly Medicated Approach\n\nAt Highly Medicated, we believe in the power of nature to heal. Our CannaSalve range is crafted using full-spectrum cannabis extract combined with carefully selected botanical ingredients, creating a synergistic blend that supports your body's natural healing processes.\n\nEvery batch is hand-crafted in Cape Town, ensuring quality and consistency in every jar.`,
    image: '/assets/blog/healing-topicals.jpg',
    author: 'Highly Medicated',
    published: true,
    tags: ['cannabis', 'healing', 'topicals', 'wellness'],
  },
  {
    title: 'Understanding Cannabis Laws in South Africa',
    slug: 'cannabis-laws-south-africa',
    excerpt: 'A comprehensive guide to the current cannabis regulations in South Africa and what they mean for consumers.',
    content: `The legal landscape around cannabis in South Africa has evolved significantly following the landmark 2018 Constitutional Court ruling. Here is what you need to know.\n\n## The 2018 Ruling\n\nThe Constitutional Court of South Africa ruled that the personal use, possession, and cultivation of cannabis by adults in private is not a criminal offence. This landmark decision marked a turning point for cannabis culture in the country.\n\n## What This Means for You\n\n- **Private Use**: Adults may use cannabis privately\n- **Personal Cultivation**: Growing cannabis for personal use at home is permitted\n- **Cannabis Products**: Products containing cannabis extract are increasingly available\n- **Medical Use**: South Africa has provisions for medical cannabis use\n\n## The Future of Cannabis in SA\n\nThe Cannabis for Private Purposes Bill continues to shape the regulatory framework. As the industry matures, consumers can expect clearer guidelines and more accessible products.\n\n## Our Commitment\n\nHighly Medicated operates within the legal framework of South Africa, providing cannabis-infused wellness products that prioritize quality, safety, and transparency.`,
    image: '/assets/blog/cannabis-laws.jpg',
    author: 'Highly Medicated',
    published: true,
    tags: ['cannabis', 'law', 'south-africa', 'regulation'],
  },
  {
    title: 'Natural Wellness: A Holistic Approach to Healing',
    slug: 'natural-wellness-holistic-healing',
    excerpt: 'Explore the intersection of traditional African healing practices and modern cannabis-based wellness solutions.',
    content: `In South Africa, traditional healing practices have existed for thousands of years. Today, we see a beautiful convergence of ancient wisdom and modern science in the wellness space.\n\n## Traditional Meets Modern\n\nAfrican traditional medicine has long recognized the healing properties of various plants and natural substances. Cannabis, known locally by many names, has been part of this tradition for generations.\n\nModern extraction and formulation techniques now allow us to harness these properties more effectively than ever before.\n\n## The Holistic Approach\n\nTrue wellness encompasses more than just physical health. At Highly Medicated, we believe in addressing:\n\n- **Physical Well-being**: Through our healing ointments and topicals\n- **Mental Balance**: Creating moments of calm in your daily routine\n- **Spiritual Connection**: Honoring the sacred relationship between plants and people\n- **Community**: Building a supportive network of like-minded individuals\n\n## Integrating Cannabis Wellness\n\nIncorporating cannabis-based wellness products into your routine can be a gentle, natural way to support your overall health journey. Start with small amounts, listen to your body, and allow the natural compounds to work in harmony with your system.`,
    image: '/assets/blog/holistic-wellness.jpg',
    author: 'Highly Medicated',
    published: true,
    tags: ['wellness', 'holistic', 'healing', 'traditional'],
  },
];
